services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: nodemon --legacy-watch index.js
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_db
      - HOST=db
      - USER=postgres
      - PASSWORD=postgres
      - DB=app_db
      - DB_PORT=5432
      - SERVER_PORT=5001
      - DIALECT=postgres
    depends_on:
      - db

  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.client
  #   ports:
  #     - "5174:5174"
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   depends_on:
  #     - server

  db:
    image: postgres:16
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
